### ISSUE TITLE
undefined variables in `arxiv.py`

### ISSUE THREAD

**Issue by littlesulley** [golsun/StyleFusion#1]
hi, there're some undefined variables `EQN_token`,`CITE_token`, `IX_token` and `norm_sentence` in `arxiv.py`.
BTW, great work:)

**Comment by golsun** [comment]
> hi, there're some undefined variables `EQN_token`,`CITE_token`, `IX_token` and `norm_sentence` in `arxiv.py`.
> BTW, great work:)

sorry for the bug! fixed now. Please let me know if you get any issue. thanks!

**Comment by littlesulley** [comment]
sorry to bother you, but i still have some issue here.
i run `arxiv.py` and it gives some Errors such as
```
hep-th-1992/1992//9201057

Error at "source" (line 524, column 1):
unexpected Tok "source" (line 524, column 1) (CtrlSeq "end") "\\end"
expecting end of input
\end
```
and 
```
hep-th-1992/1992//9201058

Error at "source" (line 5, column 8):
unexpected phyzzx
\input phyzzx
       ^
```
i suppose something goes wrong at the following two lines of code:
> process = subprocess.Popen(cmd, stdout=subprocess.PIPE)
> process.communicate()

**Comment by golsun** [comment]
yes it will show some error message as the raw latex file is being processed. For my case, only a few of them shows errors and I simply ignored these files. I guess as long as the amount of finally extracted utterances is large enough, it's probably fine to ignore them. 

but if you keep getting these error for almost all latex files, please let me know. thanks

**Comment by littlesulley** [comment]
thanks for your reply! i found it's fine to ignore them as well !
